name: ${COMPOSE_PROJECT_NAME:-devops-infra}

include:
  - path: ./jenkins/jenkins.compose.yaml
  - path: ./plane/plane.compose.yaml

networks:
  backend:
    name: ${COMPOSE_PROJECT_NAME:-devops-infra}-backend
  proxy:
    name: ${COMPOSE_PROJECT_NAME:-devops-infra}-proxy
