name: infrastructure-pipelinse

services:
  jenkins:
    image: ivomika/jenkins:0.1
    container_name: jenkins
    restart: unless-stopped
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc/jenkins.yaml
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID:-admin}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD:-admin}
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/jcasc:/var/jenkins_home/casc:ro

volumes:
  jenkins_home:
