name: infrastructure-pipeline

include:
  - path: ./jenkins/compose.yaml
    env_file: ./jenkins/toolchain.lock
  - path: ./jenkins/agents/compose.agents.yaml
    env_file: ./jenkins/toolchain.lock
  - path: ./plane/compose.yaml
    env_file: ./plane/toolchain.lock
