ARG MAVEN_VERSION=3.9.11
ARG COMPOSE_PROJECT_NAME=devops-infra
ARG JENKINS_AGENT_SLAVE_IMAGE=jenkins-agent-slave:1.0.0

FROM maven:${MAVEN_VERSION}-eclipse-temurin-21 AS maven
FROM ${COMPOSE_PROJECT_NAME}/${JENKINS_AGENT_SLAVE_IMAGE}

USER root

COPY --from=maven /usr/share/maven /usr/share/maven

RUN ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME=/usr/share/maven

USER jenkins
