# check=skip=InvalidDefaultArgInFrom

ARG JENKINS_INBOUND_AGENT_IMAGE
FROM ${JENKINS_INBOUND_AGENT_IMAGE}

ARG CA_CERTIFICATES_VERSION
ARG CURL_VERSION
ARG DEBIAN_SNAPSHOT
ARG GIT_VERSION
ARG SOURCE_DATE_EPOCH
ARG UNZIP_VERSION
ARG XZ_UTILS_VERSION
ARG ZIP_VERSION

ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}

USER root

RUN test "${SOURCE_DATE_EPOCH}" -gt 0 \
    && sed -i \
        -e "s|http://deb.debian.org/debian-security|http://snapshot.debian.org/archive/debian-security/${DEBIAN_SNAPSHOT}|" \
        -e "s|http://deb.debian.org/debian|http://snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT}|" \
        -e "/^Signed-By:/a Check-Valid-Until: no" \
        /etc/apt/sources.list.d/debian.sources \
    && apt-get -o Acquire::Check-Valid-Until=false update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        "ca-certificates=${CA_CERTIFICATES_VERSION}" \
        "curl=${CURL_VERSION}" \
        "git=${GIT_VERSION}" \
        "unzip=${UNZIP_VERSION}" \
        "xz-utils=${XZ_UTILS_VERSION}" \
        "zip=${ZIP_VERSION}" \
    && rm -rf \
        /var/cache/apt/archives/* \
        /var/lib/apt/lists/* \
        /var/log/apt/* \
    && rm -f /var/log/dpkg.log \
    && mkdir -p /home/jenkins/agent \
    && chown -R jenkins:jenkins /home/jenkins

USER jenkins

RUN git --version \
    && curl --version \
    && unzip -v | sed -n '1p' \
    && xz --version \
    && zip --version | sed -n '1p'
