ARG JENKINS_VERSION=2.568.2

FROM jenkins/jenkins:${JENKINS_VERSION}-jdk21

COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt
