services:
  slave:
    image: ${COMPOSE_PROJECT_NAME:-devops-infra}/${JENKINS_AGENT_SLAVE_IMAGE:-jenkins-agent-slave:1.0.0}
    build:
      context: ./slave
      dockerfile: dockerfile

  java:
    image: ${COMPOSE_PROJECT_NAME:-devops-infra}/${JENKINS_AGENT_JAVA_IMAGE:-jenkins-agent-java:1.0.0}
    build:
      context: ./java
      dockerfile: dockerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-devops-infra}
        JENKINS_AGENT_SLAVE_IMAGE: ${JENKINS_AGENT_SLAVE_IMAGE:-jenkins-agent-slave:1.0.0}

  node:
    image: ${COMPOSE_PROJECT_NAME:-devops-infra}/${JENKINS_AGENT_NODE_IMAGE:-jenkins-agent-node:1.0.0}
    build:
      context: ./node
      dockerfile: dockerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-devops-infra}
        JENKINS_AGENT_SLAVE_IMAGE: ${JENKINS_AGENT_SLAVE_IMAGE:-jenkins-agent-slave:1.0.0}

  flutter:
    image: ${COMPOSE_PROJECT_NAME:-devops-infra}/${JENKINS_AGENT_FLUTTER_IMAGE:-jenkins-agent-flutter:1.0.0}
    build:
      context: ./flutter
      dockerfile: dockerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-devops-infra}
        JENKINS_AGENT_SLAVE_IMAGE: ${JENKINS_AGENT_SLAVE_IMAGE:-jenkins-agent-slave:1.0.0}
