ARG JENKINS_CONTROLLER_BASE_IMAGE
FROM ${JENKINS_CONTROLLER_BASE_IMAGE}

ARG DEBIAN_SNAPSHOT
ARG GIT_VERSION
ARG OPENSSH_CLIENT_VERSION
ARG JENKINS_PLUGIN_DOWNLOAD_URL
ARG JENKINS_PLUGIN_INFO_URL
ARG SOURCE_DATE_EPOCH

ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}

USER root

RUN test "${SOURCE_DATE_EPOCH}" -gt 0 \
    && sed -i \
        -e "s|http://deb.debian.org/debian-security|http://snapshot.debian.org/archive/debian-security/${DEBIAN_SNAPSHOT}|" \
        -e "s|http://deb.debian.org/debian|http://snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT}|" \
        -e "/^Signed-By:/a Check-Valid-Until: no" \
        /etc/apt/sources.list.d/debian.sources \
    && apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -y --no-install-recommends \
        "git=${GIT_VERSION}" \
        "openssh-client=${OPENSSH_CLIENT_VERSION}" \
    && rm -rf \
        /var/cache/apt/archives/* \
        /var/lib/apt/lists/* \
        /var/log/apt/* \
    && rm -f /var/log/dpkg.log

USER jenkins

COPY plugins/plugins.lock.txt /usr/share/jenkins/ref/plugins.lock.txt
COPY plugins/plugins.sha256 /usr/share/jenkins/ref/plugins.sha256

RUN jenkins-plugin-cli \
        --plugin-file /usr/share/jenkins/ref/plugins.lock.txt \
        --jenkins-update-center-download-url "${JENKINS_PLUGIN_DOWNLOAD_URL}" \
        --jenkins-plugin-info "${JENKINS_PLUGIN_INFO_URL}" \
        --latest false \
    && cd /usr/share/jenkins/ref/plugins \
    && sha256sum --check ../plugins.sha256 \
    && find . -exec touch -h -d "@${SOURCE_DATE_EPOCH}" {} +
