global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: containers
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: host
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: jenkins
    metrics_path: /prometheus
    static_configs:
      - targets: ["jenkins-controller:8080"]

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ["http://jenkins-controller:8080/login"]
        labels:
          service: Jenkins
      - targets: ["http://plane-proxy:80/"]
        labels:
          service: Plane
      - targets: ["http://docmost:3000/"]
        labels:
          service: Docmost
      - targets: ["http://nexus:8081/"]
        labels:
          service: Nexus
    relabel_configs:
      - source_labels: [__address__]
        target_label: target
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [service]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox-projects
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files: ["/etc/prometheus/targets/projects.yml"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: target
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [project, component]
        separator: /
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
